version: "3.9"

services:
  db:
    container_name: db_events
    image: postgres:14.0-alpine
    hostname: postgres
    command:
      - postgres
      # the following lines tell pg server to adjust the TCP keepalive settings explicitly
      # instead of reading from the container default, which is likely idle=7200 (seconds).
      # The default value in the container is usually much larger than docker-swarm's IPVS default,
      # which is 900. (And this is the culprit of the connection will be closed after ~15mins)
      - -c
      - 'tcp_keepalives_idle=600'
      - -c
      - 'tcp_keepalives_interval=30'
      - -c
      - 'tcp_keepalives_count=10'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5440:${POSTGRES_PORT}
    restart: always

  web:
    container_name: web
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    restart: always


  controller:
    container_name: event_controller
    build: .
#    environment:
#      - DB_SERVER=kanban-postgres
    depends_on:
      - db
    links:
      - db
    restart: always
    command: python server/event_controller.py
